### PR TITLE
Create igstory.js

### PR DESCRIPTION
**Pull request by Piyoxz**
Video stories instagram not photo

### CODE REVIEW

**Comment by Piyoxz** [comment]
> Why did you close the pull request?

i dont know , I'm afraid it already has a feature

**Comment by moo-d** [comment]
> > Why did you close the pull request?
> 
> i dont know , I'm afraid it already has a feature

I have tried your code, but there is an error.

**Comment by Piyoxz** [comment]
> > > Why did you close the pull request?
> > 
> > 
> > i dont know , I'm afraid it already has a feature
> 
> I have tried your code, but there is an error.

where ?

**Comment by Piyoxz** [comment]
i forgot to change event in function . should use username , not url

**Comment by Piyoxz** [comment]
> > > Why did you close the pull request?
> > 
> > 
> > i dont know , I'm afraid it already has a feature
> 
> I have tried your code, but there is an error.
hgawda
it is working

**Pull request merged**
